// LLM-based summaries for Safe
// Auto-generated by setup_summaries.py

methods {
    // NONDET summaries

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     * AI Analysis: The method contains inline assembly blocks that use the `mload` instruction to read the contract signature length from memory.
     */
    function Safe.checkContractSignature(address owner, bytes32 dataHash, bytes memory signatures, uint256 offset) internal => NONDET;


}
